### ISSUE TITLE
Issue is still occurring in latest version

### ISSUE THREAD

**Issue by JAYTARPARA** [ggichure/hexcolor#7]
Issue is still occurring in latest version
![WhatsApp Image 2021-03-01 at 12 43 21 PM](https://user-images.githubusercontent.com/11882157/109466524-d822bf80-7a8f-11eb-8abf-ec781586ed20.jpeg)

_Originally posted by @JAYTARPARA in https://github.com/ggichure/hexcolor/issues/1#issuecomment-787730172_

**Comment by ggichure** [comment]
please check this [swift issue flutter fix](https://github.com/ko2ic/image_downloader/wiki#your-appdelegate-is-the-case-of-objective-c )

This problem is on the flutter side, so all plugins created with swift have the same problem. https://github.com/flutter/flutter/issues/25676#issuecomment-449543241
